# Config file for DeepForest-pytorch module

train:
    #Cpu workers for data loaders
    workers: 1
    
    #Optomizer  initial learning rate
    lr: 0.001

    #Path to validation annotations for callback
    validation_callback: 
    
    #Print loss every n epochs
    print_freq: 1
